/**
 * Config Guide Resource
 *
 * Hardcoded reference for all configuration files in the framework.
 * Registers: tsdevstack://guide/config
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

const CONFIG_CONTENT = `# tsdevstack Configuration Reference

## \`.tsdevstack/config.json\`
Main project configuration. Source of truth for services.

**Managed by:** \`add_service\`, \`remove_service\`, \`register_detached_worker\`, \`unregister_detached_worker\`, \`add_bucket_storage\`, \`remove_bucket_storage\`
**Never edit directly** — use CLI commands.

Structure:
- \`project\` — name, version, description
- \`framework\`: version, packageScope (@tsdevstack), template; optional \`apiKeys.ipLimitPerMinute\` (per-IP ceiling on partner API routes, positive integer, default 600; the one setting users edit by hand, then regenerate Kong)
- \`cloud.provider\` — active cloud provider (gcp, aws, azure)
- \`services[]\` — all services and workers:
  - NestJS: \`{ name, type: "nestjs", port, globalPrefix, hasDatabase?, databaseType? }\`
  - Next.js: \`{ name, type: "nextjs", port, hasDatabase: false }\`
  - SPA: \`{ name, type: "spa", port, hasDatabase: false }\`
  - Worker: \`{ name, type: "worker", baseService: "parent-service-name" }\`
- \`storage.buckets[]\` — object storage buckets (managed by \`add_bucket_storage\` / \`remove_bucket_storage\`):
  - Each entry: \`{ name: "bucket-name" }\` (kebab-case, 2-30 chars)
  - When buckets exist: docker-compose gets MinIO (S3-compatible, ports 9000+9001), secrets get \`STORAGE_*\` entries
  - Cloud name derived: \`{project}-{name}-{env}\` (max 63 chars)
  - See docs-site at \`/features/object-storage\` for full storage documentation

## \`.tsdevstack/infrastructure.json\`
Per-environment infrastructure settings. **This is a user-created file** — NOT generated by the framework.

**Created by:** The user (or AI when asked). Used by \`infra:generate\` and \`infra:deploy\`.
**Never generated** — unlike config.json (managed by CLI commands), the user creates and edits this file directly.

### How to create it
\`\`\`json
{
  "$schema": "./infrastructure.schema.json",
  "version": "1.0.0",
  "dev": {
    "accessControl": { "noIndex": true },
    "auth-service": { "minInstances": 0, "maxInstances": 5, "cpu": "1", "memory": "512Mi" },
    "frontend": { "domain": "example.com", "minInstances": 0, "maxInstances": 5, "cpu": "1", "memory": "512Mi" },
    "kong": { "minInstances": 0, "maxInstances": 5, "cpu": "1", "memory": "1Gi" },
    "database": { "tier": "db-f1-micro", "deletionProtection": false },
    "redis": { "memoryGb": 1, "tier": "BASIC" }
  }
}
\`\`\`

**Key rules:**
- \`$schema\` MUST reference \`./infrastructure.schema.json\` (for IDE autocomplete + validation)
- \`version\` is always \`"1.0.0"\`
- Top-level keys after version are environment names: \`dev\`, \`staging\`, \`prod\`
- Within each env: named service overrides + \`database\`, \`redis\`, \`kong\`, \`loadBalancer\`, \`accessControl\`, \`security\`, \`scheduledJobs\`
- Service names must match services in \`config.json\`
- **\`minInstances: 0\` (scale to zero) works on GCP and Azure only.** On AWS every service and \`kong\` needs \`minInstances\` of 1 or more; \`0\` fails \`infra:generate\`, \`infra:plan\`, \`infra:deploy\` and \`infra:status\` with a hint (the AWS schema has \`minimum: 1\`). The example above is a GCP/Azure dev setup.
- \`kong.maxUploadSize\` sets the gateway's request body limit in the cloud (default \`"10m"\`); locally there is no limit

### Valid values
Read \`infrastructure.schema.json\` for the definitive list. Key values:
- **CPU:** \`"0.25"\`, \`"0.5"\`, \`"1"\`, \`"2"\`, \`"4"\`, \`"8"\`
- **Memory:** \`"256Mi"\`, \`"512Mi"\`, \`"0.5Gi"\`, \`"1Gi"\`, \`"2Gi"\`, \`"4Gi"\`, \`"8Gi"\`
- **DB tier (GCP):** \`"db-f1-micro"\`, \`"db-g1-small"\`, \`"db-n1-standard-1"\`, \`"db-n1-standard-2"\`, \`"db-n1-standard-4"\`
- **Redis tier (GCP):** \`"BASIC"\`, \`"STANDARD_HA"\`
- Provider-specific values differ — check the schema or provider override files

### Access control & security
- **\`accessControl.noIndex\`** — Adds \`X-Robots-Tag: noindex, nofollow\` header to all responses. Use on non-prod to prevent search engine indexing.
- **\`security.waf.customRules\`** — Custom Cloud Armor WAF rules for rate limiting, IP blocking, or traffic filtering. Each rule has a \`name\`, \`priority\` (use 800-899 for custom), \`action\` (\`allow\`, \`deny(403)\`, \`deny(404)\`, \`deny(429)\`, \`throttle\`), and a CEL \`expression\`. For \`throttle\` actions, add \`rateLimit: { count, intervalSec }\`. Read the schema for full options.

### Provider-specific overrides
\`infrastructure.gcp.json\`, \`infrastructure.aws.json\`, \`infrastructure.azure.json\` — same structure as \`infrastructure.json\` but provider-specific values (different DB tiers, Redis tiers, etc.). Base config is merged with provider config at deploy time.

## \`.tsdevstack/infrastructure.schema.json\`
JSON Schema defining all valid fields and values for \`infrastructure.json\`. **Generated by \`infra:init\`** — only exists after infrastructure initialization. The schema documents every field, enum value, min/max, and description. AI agents should read this for definitive valid values.

## \`.tsdevstack/secret-map.json\`
Maps secrets to services. Auto-generated by \`generate-secrets\`.

Shows which environment variables each service receives. Critical for debugging "service X doesn't have secret Y" issues.

## \`.tsdevstack/ci.json\`
CI/CD workflow configuration. Provider (github), environments to deploy.

## \`.tsdevstack/.credentials.{provider}.json\` (gitignored)
Cloud provider credentials per environment. Created by \`cloud:init\`. Contains keys for dev/staging/prod environments.

## \`.secrets.user.json\` (gitignored)
User-defined secrets and service assignments. This is the file users edit.

Structure:
- \`secrets\` — key-value pairs for custom secrets (DOMAIN, RESEND_API_KEY, etc.). With the auth template it also has \`ADMIN_EMAILS\` (comma-separated; a confirmed user listed there becomes ADMIN at login; scoped to the auth service, and in the cloud stored in the auth-service scope)
- Per-service entries with \`secrets\` array listing which keys that service needs

## \`.secrets.tsdevstack.json\` (gitignored, auto-generated)
Framework-generated secrets. NEVER edit — regenerated by \`generate-secrets\`.
Contains JWT keys, database passwords, service API keys, service URLs.

## \`.secrets.local.json\` (gitignored, auto-generated)
Merged output of \`.secrets.tsdevstack.json\` + \`.secrets.user.json\`. Injected into Docker containers.

## Generated Files (NEVER edit)
| File | Generated by | Purpose |
|------|-------------|---------|
| \`docker-compose.yml\` | \`generate_docker_compose\` | Local development containers |
| \`kong.tsdevstack.yml\` | \`generate_kong\` | Kong gateway routes (from OpenAPI specs) |
| \`.secrets.tsdevstack.json\` | \`generate_secrets\` | Framework secrets |
| \`.secrets.local.json\` | \`generate_secrets\` | Merged secrets for Docker |
| \`.secrets.user.example.json\` | \`generate_secrets\` | Stripped copy of user secrets (empty values) — committed to git, acts like \`.env.example\` |
| \`infrastructure/terraform/{env}/\` | \`infra:generate\` | Terraform configs |
| \`infrastructure/kong/{env}/\` | \`infra:generate-kong\` | Cloud Kong config (committed) |
| \`infrastructure/kong/Dockerfile\`, \`.dockerignore\` | \`generate_kong\` / \`sync\` | Kong image (same definition locally and in the cloud; committed) |
| \`infrastructure/kong/kong-plugins/\`, \`declarative/\` | \`generate_kong\` / \`sync\` | Kong image build context (gitignored; a fresh clone needs \`sync\` before \`docker compose up\`) |

## Override Files (edit these)
| File | Merged with | Purpose |
|------|-------------|---------|
| \`kong.user.yml\` | \`kong.tsdevstack.yml\` | Global plugins, custom Kong services. Its global \`rate-limiting\` also sets the default per-key limits on partner routes. Its \`request-transformer\` must only handle \`X-Kong-Trust\` and \`X-Kong-Request-Id\`. \`consumers\` with \`keyauth_credentials\` no longer work (generation warns); partner keys come from the auth service admin API |
| \`kong-plugins/\` (project root) | the Kong image | Your own Kong Lua plugins, one folder per plugin (\`handler.lua\`, \`schema.lua\`); enable them in \`kong.user.yml\` |
| \`docker-compose.user.yml\` | \`docker-compose.yml\` | Custom Docker config |
| \`.secrets.user.json\` | \`.secrets.tsdevstack.json\` | Your secrets and assignments |`;

export function registerGuideConfigResource(server: McpServer): void {
  server.registerResource(
    'guide-config',
    'tsdevstack://guide/config',
    {
      description:
        'Config files reference: every config file, its structure, how to extend it, and which CLI command manages it.',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          text: CONFIG_CONTENT,
          mimeType: 'text/markdown',
        },
      ],
    }),
  );
}
