/**
 * Core Guide Resource
 *
 * Hardcoded framework guide: project structure, service types, key principles, anti-patterns.
 * Registers: tsdevstack://guide
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

const GUIDE_CONTENT = `# tsdevstack Framework Guide

## Project Structure
- \`apps/\` — Microservices and frontends (NestJS, Next.js, SPA)
- \`packages/\` — Shared libraries and CLI packages (new packages go here, scaffold with rslib)
- \`.tsdevstack/\` — Framework configuration (config.json, infrastructure.json, credentials, secret-map)
- \`docs/\` — Documentation
- \`infrastructure/\` — GENERATED Terraform and Kong files, including the Kong image \`Dockerfile\` (never edit directly)
- \`kong-plugins/\` (optional, committed): your own Kong Lua plugins, one folder per plugin; built into the gateway image locally and in the cloud

## Service Types
- \`nestjs\` — Backend API service. Has globalPrefix, optional database, OpenAPI spec, Kong routes.
- \`nextjs\` — Server-rendered frontend (Next.js App Router).
- \`spa\` — Single-page application (Rsbuild). No server-side rendering.
- \`worker\` — Detached background job processor. Shares Docker image with its base NestJS service, runs with different entrypoint (\`dist/worker.js\`).

## Key Principles
- **Single source of truth:** Service names come from \`package.json\`. Config derives from \`.tsdevstack/config.json\`. No magic strings.
- **Convention over configuration:** Strict naming (kebab-case), everything derived automatically.
- **Generated files are read-only:** Files in \`infrastructure/\`, \`docker-compose.yml\`, \`kong.tsdevstack.yml\`, \`.secrets.tsdevstack.json\` are all generated by CLI commands. Edit the generators or config, not the output.
- **Override files are yours:** \`kong.user.yml\`, \`docker-compose.user.yml\`, \`.secrets.user.json\` — these are merged with generated files and preserved across regenerations.

## Anti-Patterns (DO NOT DO THESE)
- NEVER edit \`config.json\` directly to add services or workers — use \`add_service\` or \`register_detached_worker\`
- NEVER edit \`config.json\` directly to add or remove storage buckets — use \`add_bucket_storage\` / \`remove_bucket_storage\`
- NEVER edit \`config.json\` directly to add, remove, or update messaging topics — use \`add_messaging_topic\` / \`remove_messaging_topic\` / \`update_messaging_topic\`
- NEVER edit files in \`infrastructure/terraform/\` or \`infrastructure/kong/\` (including \`infrastructure/kong/Dockerfile\`): they're generated. Change the inputs instead (\`infrastructure.json\`, \`kong.user.yml\`, \`kong-plugins/\`, decorators) and regenerate
- NEVER install npm packages for things nest-common already provides (Redis, auth guards, logging, rate limiting, observability, BullMQ config, service clients, **object storage**, **async messaging**)
- NEVER install \`@aws-sdk/client-s3\`, \`@google-cloud/storage\`, or \`@azure/storage-blob\` directly — use nest-common's \`StorageModule\` which provides a unified \`StorageProvider\` interface across all providers
- NEVER create a worker by copying service boilerplate — use \`register_detached_worker\` to add to config, then create \`worker.ts\` and \`worker.module.ts\` using nest-common's \`startWorker()\` wrapper
- NEVER deploy a new service/worker with \`deploy_services\` — new services need \`infra_deploy\` (Terraform must create the container runtime first)
- NEVER shell out to \`aws\`, \`gcloud\`, or \`az\` CLI tools in source code — use cloud provider SDKs. CLI tools are only available locally.
- NEVER use \`process.env\` to read secrets in NestJS services — inject \`SecretsService\` and use \`await this.secrets.get('KEY')\`
- NEVER edit \`.secrets.tsdevstack.json\` — it's auto-generated. Put your secrets in \`.secrets.user.json\`

## OpenAPI Decorators Drive Everything
NestJS OpenAPI/Swagger decorators are NOT just for documentation — they drive the entire gateway:
1. \`@ApiOperation()\` on a controller method → the endpoint exists in OpenAPI spec
2. \`generate_kong\` reads the OpenAPI spec → generates Kong routes. Routes are exact: the path plus its declared methods (and \`OPTIONS\`). Other paths, extra segments, trailing slashes and other methods get 404 from Kong.
3. \`@ApiBearerAuth()\` → Kong adds JWT validation to that route (the backend \`AuthGuard\` is already global; no \`@UseGuards\` needed). \`@Roles('ADMIN')\` restricts it to a role.
4. \`@PartnerApi()\` → Kong exposes that one operation at \`/api\` + its path with API key auth; partner keys reach nothing else. Keys are runtime data (auth service admin API \`/auth/v1/admin/api-keys\`, checked by Kong against Redis), not config or secrets
5. \`@Public()\` → no auth; without it (and without \`@ApiBearerAuth()\`) the backend answers 401
6. \`generate_client\` reads the OpenAPI spec → generates TypeScript HTTP client + DTOs

This means: an endpoint missing from the OpenAPI spec gets no Kong route (404 through the gateway) and no client types, and a new endpoint is unreachable until the Kong config is regenerated. Decorators are the source of truth for the API contract.

## Gateway Trust
- Backends trust identity only from Kong: \`AuthGuard\` checks the \`X-Kong-Trust\` token first and only then reads the user (\`req.user\`) or the partner key (\`req.apiKey\`, \`@Partner()\`). Direct calls to \`localhost:300x\` with identity headers get 401; internal calls use the service \`x-api-key\`.
- Kong removes identity headers sent by clients before any auth plugin runs.
- The gateway image is generated (\`infrastructure/kong/Dockerfile\`, same image locally and in the cloud). A fresh clone needs \`sync\` (or \`generate_kong\`) before \`docker compose up\`.

## Secrets System
- Three-file merge: \`.secrets.tsdevstack.json\` (framework, auto-generated) + \`.secrets.user.json\` (yours) → \`.secrets.local.json\` (merged output)
- Framework secrets (JWT keys, DB passwords, service API keys, service URLs) are auto-generated — don't touch them
- User secrets (third-party API keys, custom config) go in \`.secrets.user.json\`. Partner API keys are NOT secrets: never put them there or in \`kong.user.yml\` consumers (static keys were removed)
- Each service only sees secrets assigned to it (scoping via \`secret-map.json\`)
- Cloud: \`cloud_secrets_push\` prompts for 3 values (DOMAIN, RESEND_API_KEY, EMAIL_FROM) and auto-derives everything else. With the auth template it also offers \`ADMIN_EMAILS\` (auth-service scope, first admins) when set locally; otherwise set it with \`cloud_secrets_set ADMIN_EMAILS --service auth-service --env {env}\`

## Docs-Site Reference
The framework has a documentation site with detailed guides. When deployed, reference these for deeper reading:
- **Local development:** \`/local-development/tech-stack\`, \`/local-development/debugging\`, \`/local-development/adding-apps\`
- **Secrets:** \`/secrets/how-secrets-work\`, \`/secrets/local-secrets\`, \`/secrets/user-vs-framework\`, \`/secrets/cloud-secrets\`
- **Authentication:** \`/authentication/overview\`, \`/authentication/jwt-tokens\`, \`/authentication/protected-routes\`, \`/authentication/session-management\`
- **Building APIs:** \`/building-apis/openapi-decorators\`, \`/building-apis/gateway-routing\`, \`/building-apis/dto-generation\`, \`/building-apis/swagger-docs\`
- **Infrastructure:** \`/infrastructure/cicd-setup\`, \`/infrastructure/domain-setup\`, \`/infrastructure/environments\`, \`/infrastructure/service-configuration\`
- **Observability:** \`/features/observability\`
- **Object Storage:** \`/features/object-storage\`
- **Async Messaging:** \`/features/async-messaging\`
- **Customization:** \`/customization/kong-customization\`, \`/customization/docker-overrides\`, \`/customization/framework-files\`, \`/customization/escape-hatches\`
- **Provider-specific:** \`/infrastructure/providers/gcp/\`, \`/infrastructure/providers/aws/\`, \`/infrastructure/providers/azure/\`

## Object Storage
- \`add_bucket_storage\` / \`remove_bucket_storage\` manage storage buckets in config.json
- Locally: MinIO (S3-compatible) runs in Docker on ports 9000 (API) + 9001 (console). Auto-generated in docker-compose when any bucket exists.
- NestJS: \`StorageModule.forRoot({ buckets: ['name'] })\` + \`@InjectStorage('name')\` → unified \`StorageProvider\` interface
- StorageProvider methods: upload, download, downloadStream, delete, list, copy, getMetadata, getPresignedUrl, exists, getNativeClient
- Provider auto-detected from \`SECRETS_PROVIDER\`: \`local\`/\`aws\` → S3 adapter, \`gcp\` → GCS adapter, \`azure\` → Azure Blob adapter
- Cloud: \`infra_deploy\` creates cloud buckets (S3/GCS/Azure Blob) via Terraform and syncs \`STORAGE_BUCKET_*\` secrets
- STORAGE_* secrets are shared-scope (auto-assigned to ALL services via secret-map) — no need to manually assign them in \`.secrets.user.json\`
- Azure also gets \`AZURE_STORAGE_ACCOUNT_NAME\` injected as an env var (not a secret)

## Async Messaging
- \`add_messaging_topic\` / \`remove_messaging_topic\` / \`update_messaging_topic\` manage messaging topics in config.json
- Uses Redis Streams — same Redis instance as BullMQ and caching. No new infrastructure.
- NestJS: \`MessagingModule.forRoot({ consumerGroup: 'service-name', topics: ['topic-name'] })\` + \`@OnMessage('topic-name')\` decorator
- Publishing: inject \`MessagingService\` and call \`messaging.publish('topic-name', data)\`
- Handler contract: return = XACK (acknowledged), throw = retry (stays pending), 3 failures = DLQ
- Stream key format: \`{project}:messaging:{topicName}\`, consumer group: \`{project}:messaging:{topicName}:{serviceName}\`
- **Messaging vs BullMQ:** Messaging = inter-service event broadcasting (pub/sub, every subscriber gets every message). BullMQ = intra-service job queues (one consumer per job). They complement each other.
- \`update_messaging_topic\` uses **replace semantics** — pass the complete desired list of publishers/subscribers, not additions
- No Terraform, no new secrets, no new env vars, no docker-compose changes

## Deployment Model
- \`infra_deploy\` = full deploy (Terraform infra + build Docker + push + deploy all services + Kong + LB + storage buckets). Required for new services/workers and new storage buckets.
- \`deploy_services\` = code push only (build + push + deploy). For code updates to existing services. Supports \`--service\` for single service.
- Kong gateway changes (routes/decorators, \`kong.user.yml\`, \`kong-plugins/\`, CLI upgrades) = \`infra_generate_kong\` → \`infra_build_kong\` → \`deploy_kong\`. \`deploy_kong\` alone deploys an already built image. \`infra_deploy\` runs all three.
- \`deploy_lb\` = deploy/update load balancer. After changing domains.
- New services/workers ALWAYS require \`infra_deploy\` because Terraform must create the container runtime.
- New storage buckets require \`infra_deploy\` because Terraform must create the cloud bucket and sync \`STORAGE_BUCKET_*\` secrets.
- Code updates to existing services: \`deploy_services\` is faster.`;

export function registerGuideResource(server: McpServer): void {
  server.registerResource(
    'guide',
    'tsdevstack://guide',
    {
      description:
        'Core framework concepts: project structure, service types, key principles, anti-patterns, secrets system, deployment model.',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          text: GUIDE_CONTENT,
          mimeType: 'text/markdown',
        },
      ],
    }),
  );
}
