/**
 * Project State Resources
 *
 * Dynamic file-read resources for project configuration files.
 * Registers: tsdevstack://config, tsdevstack://infrastructure,
 * tsdevstack://infrastructure-schema, tsdevstack://ci
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

function readProjectFile(relativePath: string): string | null {
  try {
    return readFileSync(join(process.cwd(), relativePath), 'utf-8');
  } catch {
    return null;
  }
}

export function registerProjectStateResources(server: McpServer): void {
  server.resource(
    'config',
    'tsdevstack://config',
    {
      description:
        'Project name, services, types, ports — the main project configuration.',
    },
    async (uri) => {
      const content = readProjectFile('.tsdevstack/config.json');
      return {
        contents: [
          {
            uri: uri.href,
            text:
              content ??
              'config.json not found. Run `npx tsdevstack init` to create a project.',
            mimeType: 'application/json',
          },
        ],
      };
    },
  );

  server.resource(
    'infrastructure',
    'tsdevstack://infrastructure',
    {
      description:
        'Per-environment infrastructure settings (DB tiers, domains, scaling). User-created file.',
    },
    async (uri) => {
      const content = readProjectFile('.tsdevstack/infrastructure.json');
      return {
        contents: [
          {
            uri: uri.href,
            text:
              content ??
              'infrastructure.json not found. This is a user-created file — see the guide/config resource for how to create it.',
            mimeType: 'application/json',
          },
        ],
      };
    },
  );

  server.resource(
    'infrastructure-schema',
    'tsdevstack://infrastructure-schema',
    {
      description:
        'Valid fields and values for infrastructure.json. Generated by `infra:init`. Only exists after initialization.',
    },
    async (uri) => {
      const content = readProjectFile('.tsdevstack/infrastructure.schema.json');
      return {
        contents: [
          {
            uri: uri.href,
            text:
              content ??
              'infrastructure.schema.json not found. Run `npx tsdevstack infra:init --env <env>` to generate the schema.',
            mimeType: 'application/json',
          },
        ],
      };
    },
  );

  server.resource(
    'ci',
    'tsdevstack://ci',
    {
      description:
        'CI/CD configuration — environments, provider, workflow settings.',
    },
    async (uri) => {
      const content = readProjectFile('.tsdevstack/ci.json');
      return {
        contents: [
          {
            uri: uri.href,
            text:
              content ??
              'ci.json not found. Run `npx tsdevstack infra:init-ci --github` to initialize CI/CD.',
            mimeType: 'application/json',
          },
        ],
      };
    },
  );
}
